### ISSUE TITLE
nohup.out 输出卡在某个进度 57% 位置

### ISSUE THREAD

**Issue by wavelistent0me** [cwyalpha/Langchain-Chatchat-Colab#2]
![微信截图_20231114161527](https://github.com/cwyalpha/Langchain-Chatchat-Colab/assets/74590962/e0e57df5-252f-4fa2-aef0-b2bf98f8744e)

**Comment by wavelistent0me** [comment]
![微信截图_20231114161527](https://github.com/cwyalpha/Langchain-Chatchat-Colab/assets/74590962/e3833dbf-bc07-4599-8dfb-5239de3c0f51)

**Comment by wavelistent0me** [comment]
转发的外网链接输入ip后也一直转圈等待

**Comment by python-scrapy** [comment]
转发的外网链接输入ip后也一直转圈等待  
![Uploading 微信截图_20240109140752.png…]()

**Comment by cwyalpha** [comment]
已修复，Langchain-chatchat不再支持int4的模型，现修改为Qwen/Qwen1.5-1.8B-Chat后可在colab运行。

**Comment by cwyalpha** [comment]
已修复
原Langchain-chatchat不再支持int4模型，现修改为Qwen/Qwen1.5-1.8B-Chat后可在colab运行

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aquamon, @hui0xin, @atpalmer, @sunho-lee, @musik, @Sivasankaramalan, @myoldfycy318, @holy-motors, @gottemmcoach357, @KrishJani, @atick-faisal, @tayzlor, @new4761, @rikhoffbauer, @randomshana1, @jianglei260, @rogerli0222, @dannyp777, @code-stan, @xuzeyu91, @eliabecardoso, @chodenke, @taiguangyin, @WindCore, @DosWorld, @Chi-Kai, @faruk13, @Macadacious, @anushkak09, @hmasum52, @RinatValiullov, @pedrotorreao, @MatteoDrago, @lebe24, @whatthebrain, @KingJA, @gcdeng, @mvrtynvx, @cluo, @bluetoothfx, @mlliarm, @xegg, @zero-shubham, @fq07, @WVWVWVHO, @akioniace, @crocla, @Fz3r0, @harryptoe, @forrestchang
