### ISSUE TITLE
请问IP要写特定的吗，输入自己的Error了

### ISSUE THREAD

**Issue by babyblue233** [cwyalpha/Langchain-Chatchat-Colab#3]
第一次用colab+第一次部署langchain，可能是个傻问题但是拜托解答，感谢！

**Comment by babyblue233** [comment]
Error: endpoint IP is not correct. Please try again or contact whoever gave you this link for the correct public IP.

**Comment by axdwss** [comment]
> 第一次用colab+第一次部署langchain，可能是个傻问题但是拜托解答，感谢！
“”““
print("Password/Enpoint IP for localtunnel is:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))
””
colab有输出，复制过去就好
